// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForInsertSamples implements pgx.CopyFromSource.
type iteratorForInsertSamples struct {
	rows                 []InsertSamplesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSamples) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSamples) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TimeStamp,
		r.rows[0].Eeg1,
		r.rows[0].Eeg2,
		r.rows[0].Ecg,
		r.rows[0].RecordingID,
	}, nil
}

func (r iteratorForInsertSamples) Err() error {
	return nil
}

func (q *Queries) InsertSamples(ctx context.Context, arg []InsertSamplesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"samples"}, []string{"time_stamp", "eeg1", "eeg2", "ecg", "recording_id"}, &iteratorForInsertSamples{rows: arg})
}
