// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Recording struct {
	ID               int32
	TimeFrom         pgtype.Timestamp
	TimeTo           pgtype.Timestamp
	StatePrediction  string
	ActionPrediction string
	UserID           int32
}

type Sample struct {
	TimeStamp   pgtype.Timestamp
	Eeg1        float64
	Eeg2        float64
	Ecg         float64
	RecordingID int32
}

type User struct {
	ID        int32
	FirstName string
	LastName  string
}
