// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name)
VALUES ($1, $2)
RETURNING id, first_name, last_name
`

type CreateUserParams struct {
	FirstName string
	LastName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.FirstName, arg.LastName)
	var i User
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllRecordings = `-- name: GetAllRecordings :many
SELECT id, time_from, time_to, state_prediction, action_prediction, user_id FROM recordings
`

func (q *Queries) GetAllRecordings(ctx context.Context) ([]Recording, error) {
	rows, err := q.db.Query(ctx, getAllRecordings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recording
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.TimeFrom,
			&i.TimeTo,
			&i.StatePrediction,
			&i.ActionPrediction,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, first_name, last_name FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordingByID = `-- name: GetRecordingByID :one
SELECT id, time_from, time_to, state_prediction, action_prediction, user_id FROM recordings WHERE id = $1
`

func (q *Queries) GetRecordingByID(ctx context.Context, id int32) (Recording, error) {
	row := q.db.QueryRow(ctx, getRecordingByID, id)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.TimeFrom,
		&i.TimeTo,
		&i.StatePrediction,
		&i.ActionPrediction,
		&i.UserID,
	)
	return i, err
}

const getSamplesByRecordingID = `-- name: GetSamplesByRecordingID :many
SELECT time_stamp, eeg1, eeg2, ecg, recording_id FROM samples WHERE recording_id = $1 ORDER BY time_stamp
`

func (q *Queries) GetSamplesByRecordingID(ctx context.Context, recordingID int32) ([]Sample, error) {
	rows, err := q.db.Query(ctx, getSamplesByRecordingID, recordingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sample
	for rows.Next() {
		var i Sample
		if err := rows.Scan(
			&i.TimeStamp,
			&i.Eeg1,
			&i.Eeg2,
			&i.Ecg,
			&i.RecordingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSamplesByUserID = `-- name: GetSamplesByUserID :many
SELECT time_stamp, eeg1, eeg2, ecg, recording_id, id, time_from, time_to, state_prediction, action_prediction, user_id FROM samples s
INNER JOIN recordings r ON r.id = s.recording_id WHERE r.user_id = $1
ORDER BY time_stamp
`

type GetSamplesByUserIDRow struct {
	TimeStamp        pgtype.Timestamp
	Eeg1             float64
	Eeg2             float64
	Ecg              float64
	RecordingID      int32
	ID               int32
	TimeFrom         pgtype.Timestamp
	TimeTo           pgtype.Timestamp
	StatePrediction  string
	ActionPrediction string
	UserID           int32
}

func (q *Queries) GetSamplesByUserID(ctx context.Context, userID int32) ([]GetSamplesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getSamplesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSamplesByUserIDRow
	for rows.Next() {
		var i GetSamplesByUserIDRow
		if err := rows.Scan(
			&i.TimeStamp,
			&i.Eeg1,
			&i.Eeg2,
			&i.Ecg,
			&i.RecordingID,
			&i.ID,
			&i.TimeFrom,
			&i.TimeTo,
			&i.StatePrediction,
			&i.ActionPrediction,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}

type InsertSamplesParams struct {
	TimeStamp   pgtype.Timestamp
	Eeg1        float64
	Eeg2        float64
	Ecg         float64
	RecordingID int32
}

const listRecordingsByUserID = `-- name: ListRecordingsByUserID :many
SELECT id, time_from, time_to, state_prediction, action_prediction, user_id FROM recordings WHERE user_id = $1 ORDER BY time_from
`

func (q *Queries) ListRecordingsByUserID(ctx context.Context, userID int32) ([]Recording, error) {
	rows, err := q.db.Query(ctx, listRecordingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recording
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.TimeFrom,
			&i.TimeTo,
			&i.StatePrediction,
			&i.ActionPrediction,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitRecording = `-- name: SubmitRecording :one
INSERT INTO recordings (time_from, time_to, user_id, state_prediction, action_prediction)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, time_from, time_to, state_prediction, action_prediction, user_id
`

type SubmitRecordingParams struct {
	TimeFrom         pgtype.Timestamp
	TimeTo           pgtype.Timestamp
	UserID           int32
	StatePrediction  string
	ActionPrediction string
}

func (q *Queries) SubmitRecording(ctx context.Context, arg SubmitRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, submitRecording,
		arg.TimeFrom,
		arg.TimeTo,
		arg.UserID,
		arg.StatePrediction,
		arg.ActionPrediction,
	)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.TimeFrom,
		&i.TimeTo,
		&i.StatePrediction,
		&i.ActionPrediction,
		&i.UserID,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET first_name = $1, last_name = $2 WHERE id = $3 RETURNING id, first_name, last_name
`

type UpdateUserParams struct {
	FirstName string
	LastName  string
	ID        int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.FirstName, arg.LastName, arg.ID)
	var i User
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}
